### ISSUE TITLE
Incompatibility with ScalaJS 1.1.0: https://raw.githubusercontent.com/scala-js/scala-js/v1.1.0/javalanglib/src/main/scala/java/lang/System.scala(186:43:IdentityHashCode): Invalid expression tree

### ISSUE THREAD

**Issue by thesamet** [scalacenter/scalajs-bundler#341]
When upgrading to ScalaJS 1.1.0 I noticed the following problem:

```
https://raw.githubusercontent.com/scala-js/scala-js/v1.1.0/javalanglib/src/main/scala/java/lang/System.scala(186:43:IdentityHashCode): Invalid expression tree
```

To reproduce:
```
// project/plugins.sbt
addSbtPlugin("org.scala-js" % "sbt-scalajs" % "1.1.0")

addSbtPlugin("ch.epfl.scala" % "sbt-scalajs-bundler" % "0.17.0")
```

```
// project/build.properties
sbt.version=1.3.10
```

```
scalaVersion := "2.13.2"

lazy val code = project
  .in(file("code"))
  .enablePlugins(ScalaJSPlugin)
  .enablePlugins(ScalaJSBundlerPlugin)
  .settings(
    scalaJSUseMainModuleInitializer := true
  )
```

Then try, `sbt test`

**Comment by cquiroz** [comment]
We just released 0.18.0 which should solve it, it may be still on its way to maven central

**Comment by thesamet** [comment]
Thanks for the quick turnaround @cquiroz . I still don't see the release on maven central. Can you double-check if it got released?

**Comment by sjrd** [comment]
It's there now.
